from django.contrib import admin
from Products.models import *
# Register your models here.
admin.site.register(Categories)
admin.site.register(Sub_Categories)
admin.site.register(Product_images)
admin.site.register(Products)
admin.site.register(Brand)
admin.site.register(discount)
admin.site.register(cupon)
admin.site.register(Supplier)
admin.site.register(Countreies)
admin.site.register(ProductAttribute)
admin.site.register(ProductType)
admin.site.register(ProductAttributeValue)
admin.site.register(ProductInventory)
admin.site.register(ProductAttributeValues)
admin.site.register(ProductTypeAttribute)
admin.site.register(Stock)
admin.site.register(Cart)
admin.site.register(CartProduct)
